// AUTO-GENERATED by wayland CLI from brief: dc-masonry
// DO NOT EDIT THIS FILE DIRECTLY.
// Changes here will be overwritten on the next scaffold.
// To update content, edit the brief JSON and re-run:
//   wayland scaffold --brief <path> --force

export type SectionCopyEntry = {
  eyebrow?: string;
  heading?: string;
  subhead?: string;
};

export type SectionCopy = {
  serviceGrid?: SectionCopyEntry;
  testimonials?: SectionCopyEntry;
  about?: SectionCopyEntry;
};

export type Business = {
  name: string;
  tagline: string;
  description: string;
  phone: string;
  email: string;
  address: string;
  hours: string;
  portraitUrl?: string;
  logoUrl?: string;
};

export type PortfolioItem = {
  title: string;
  category?: string;
  imageUrl: string;
  href?: string;
  description?: string;
};

export type Portfolio = readonly PortfolioItem[];

export type TeamMember = {
  name: string;
  role: string;
  bio: string;
  photoUrl?: string;
};

export type Team = readonly TeamMember[];

export type FaqEntry = { q: string; a: string };

export type Faq = readonly FaqEntry[];

export type Testimonial = { quote: string; author: string; role: string; company: string };

export type Testimonials = readonly Testimonial[];

export type Tier = 'foundation' | 'operator' | 'engine';

export type Archetype = 'service';

const tier: Tier = "operator";

const archetype: Archetype = "service";

const sectionCopy: SectionCopy = {};

const business: Business = {
  "name": "D.C. Masonry",
  "tagline": "The Hardscape Pros",
  "description": "Blue-collar, family-owned masonry & hardscaping — beautifying Rhode Island since 2006. Pavers, patios, walls, natural stone veneer, foundations, and site work. Free estimates.",
  "phone": "(401) 474-9343",
  "email": "dcmasonryinc@gmail.com",
  "address": "Rhode Island",
  "hours": "Free estimates — call (401) 474-9343"
};

const portfolio: Portfolio = [
  {
    "title": "Paver driveway & stone-faced home",
    "imageUrl": "/images/paver-driveway.jpg"
  },
  {
    "title": "Bluestone steps & stone risers",
    "imageUrl": "/images/bluestone-steps.jpg"
  },
  {
    "title": "Natural stone veneer wall",
    "imageUrl": "/images/stone-veneer-wall.jpg"
  },
  {
    "title": "Stone wall with copper lighting",
    "imageUrl": "/images/lantern-wall.jpg"
  }
];

const team: Team = [];

const faq: Faq = [
  {
    "q": "Do you offer free estimates?",
    "a": "Yes — every project starts with a free, no-pressure estimate. Call (401) 474-9343 and we'll come take a look."
  },
  {
    "q": "What areas do you serve?",
    "a": "Rhode Island and the surrounding areas. If you're nearby, reach out and we'll let you know."
  },
  {
    "q": "Are you licensed and insured?",
    "a": "Yes. D.C. Masonry is a Rhode Island registered general contractor, Reg. GC-29745."
  },
  {
    "q": "What kind of work do you do?",
    "a": "Pavers and patios, retaining and decorative walls, natural stone veneer, foundation resurfacing, excavation and site work, and landscaping."
  },
  {
    "q": "How long have you been in business?",
    "a": "We've been a family-owned operation beautifying Rhode Island since 2006 — over 15 years."
  }
];

const testimonials: Testimonials = [];

export const content = {
  tier,
  archetype,
  business,
  hero: {
  "headline": "Masonry & hardscaping, built to last.",
  "subhead": "Family-owned in Rhode Island since 2006. Pavers, patios, walls, natural stone veneer, foundations, and site work — done right, with free estimates.",
  "ctaPrimary": {
    "label": "Get a free estimate",
    "href": "/contact"
  },
  "ctaSecondary": {
    "label": "See our services",
    "href": "/services"
  },
  "imageUrl": "/images/paver-driveway.jpg"
},
  services: [
  {
    "name": "Pavers & Patios",
    "shortDesc": "Custom paver patios, walkways, and steps.",
    "longDesc": "Paver patios, walkways, and steps built on a proper base so they stay level and beautiful for decades.",
    "icon": "layout-grid",
    "imageUrl": "/images/bluestone-steps.jpg"
  },
  {
    "name": "Retaining & Decorative Walls",
    "shortDesc": "Walls that hold their ground and look great.",
    "longDesc": "Retaining and decorative walls engineered for stability — from garden walls to full grade changes.",
    "icon": "layers",
    "imageUrl": "/images/lantern-wall.jpg"
  },
  {
    "name": "Natural Stone Veneer",
    "shortDesc": "Real stone facing for a timeless look.",
    "longDesc": "Natural stone veneer on facades, chimneys, columns, and accent walls — the look of full stone, expertly installed.",
    "icon": "mountain",
    "imageUrl": "/images/stone-veneer-wall.jpg"
  },
  {
    "name": "Foundation & Resurfacing",
    "shortDesc": "Basement and foundation resurfacing.",
    "longDesc": "Basement and foundation resurfacing to restore and protect the base of your home, done by a licensed crew.",
    "icon": "building-2"
  },
  {
    "name": "Excavation & Site Work",
    "shortDesc": "Excavation, hoisting, and skid-steer work.",
    "longDesc": "Excavation, hoisting, and skid-steer services to prep your site and move the heavy stuff — the groundwork that lasts.",
    "icon": "truck"
  },
  {
    "name": "Landscaping & Clean-ups",
    "shortDesc": "Landscaping and seasonal yard clean-ups.",
    "longDesc": "Landscaping and yard clean-ups to finish the job and keep your property looking sharp year-round.",
    "icon": "leaf"
  }
],
  about: {
  "body": "D.C. Masonry is a blue-collar, family-owned company that's been beautifying Rhode Island since 2006. Owner Duarte Correia and his crew handle it all — paver patios and walkways, retaining and decorative walls, natural stone veneer, foundation resurfacing, excavation, and landscaping. We're a licensed Rhode Island general contractor (Reg. GC-29745), we show up when we say we will, and every job starts with a free estimate. Over 15 years in, our work speaks for itself.",
  "values": [
    {
      "title": "Family-owned since 2006",
      "body": "A blue-collar crew that treats your property like our own — 15+ years serving Rhode Island."
    },
    {
      "title": "Licensed & insured",
      "body": "Rhode Island registered general contractor, Reg. GC-29745. Done by the book, built to last."
    },
    {
      "title": "Free estimates",
      "body": "Every project starts with an honest, no-pressure estimate. Call and we'll come take a look."
    },
    {
      "title": "Hardscape specialists",
      "body": "Pavers, walls, stone veneer, and full masonry — the hardscaping that makes a yard."
    }
  ]
},
  faq,
  testimonials,
  cta: {
  "heading": "Ready to transform your outdoor space?",
  "subhead": "Get a free estimate from Rhode Island's hardscape pros — call (401) 474-9343 or send us a message.",
  "button": {
    "label": "Get a free estimate",
    "href": "/contact"
  }
},
  bento: [],
  portfolio,
  team,
  sectionCopy,
  componentVariants: {
  "hero": "split",
  "serviceGrid": "cards",
  "testimonials": "default",
  "cta": "default",
  "about": "story"
},
} as const;

export type Content = typeof content;
