// SOURCE OF TRUTH for brand-level theming.
// Generated by Wayland CLI from brief.brand. Do not edit by hand.

export const theme = {
  colors: {
    primary: '#334155',
    primaryFg: '#FFFFFF',
    accent: '#B45309',
    accentFg: '#FFFFFF',
    background: '#FFFFFF',
    foreground: '#1C1917',
    muted: '#F5F5F4',
    mutedFg: '#57534E',
    border: '#E7E5E4',
  },
  fonts: {
    heading: 'Plus Jakarta Sans, system-ui, sans-serif',
    body: 'Inter, system-ui, sans-serif',
  },
  radii: {
    sm: '0.25rem',
    md: '0.5rem',
    lg: '0.75rem',
  },
} as const;

export type Theme = typeof theme;
